### ISSUE TITLE
Not able to scan

### ISSUE THREAD

**Issue by kanumuruwe45** [Ucnt/aws-s3-data-finder#1]
Hi Team,
I have followed the steps provided and I executed one of my S3 buckets but it is throwing access denied, even after that I made both the objects and buckets to the public, still I have got access denied. 
I have tried the rerun option as well while running the bucket, even I have provided the endpoint while running find_data.py.

Any help from the team is highly appreciated!
Thank you in advance.

**Comment by Ucnt** [comment]
Can you provide the bucket name so I can test?

I could be that listing objects is denied so there's no way to see the
objects that you made public.

**Comment by kanumuruwe45** [comment]
Thank you for the response!
Bucket name is s3-object-scanning-fannie-mae
Please let me know the status once you run!

**Comment by Ucnt** [comment]
mattsvensson-ubuntu ~ $ awscligetcors s3-object-scanning-fannie-mae
An error occurred (AccessDenied) when calling the GetBucketCors operation:
Access Denied

mattsvensson-ubuntu ~ $ awscligetacl s3-object-scanning-fannie-mae
An error occurred (AccessDenied) when calling the GetBucketAcl operation:
Access Denied

mattsvensson-ubuntu ~ $ awsclilistfiles s3-object-scanning-fannie-mae 1
An error occurred (AccessDenied) when calling the ListObjects operation:
Access Denied

Getting CORS, ACL, and file lists are denied.  It looks like you made the
bucket and/or files public but that doesn't mean you can list the files in
the bucket.

If you can't list the files in the bucket, there's no way to go through the
potential keys to try to download them except a VERY expensive bruteforce.

I'll continue to conversation on LinkedIn and close this out when done.

**Comment by Ucnt** [comment]
Bucket config issue not script.
